# Generated by Django 3.2.18 on 2023-07-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('Linkedin_Link', models.URLField(blank=True)),
                ('Github_Link', models.URLField(blank=True)),
                ('Skills', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
